### ISSUE TITLE
Access denied when downloading checkpoints from S3

### ISSUE THREAD

**Issue by pzajec** [raspberryice/gen-arg#12]
Hi!

When executing 
```$ aws s3 ls s3://gen-arg-data/checkpoints/```
or 
```$ aws s3 cp s3://gen-arg-data/checkpoints/ ./ --recursive```,
I get the following error:

 "An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied". 

I am not sure if the issue is on my side?

**Comment by raspberryice** [comment]
Hi Pzajec,
I updated the permissions for the s3 bucket so that public access is available for all subdirectories as well. Could you try again?  Meanwhile, you might want to check that you have properly logged in to aws by setting up the credentials. 
If you still encounter problems, please let me know.

**Comment by pzajec** [comment]
Hi,
it appears the issue was on my side and I have successfully downloaded the checkpoints.
Thank you for the quick response! :)
